# This is an example nextest configuration for this repository. See nextest-runner/default-config.toml
# for more information.
default-profile = "diem-devtools"

[profiles.diem-devtools]
name = "diem-devtools-run"
retries = 0
failure-output = "immediate-final"
metadata-key = "diem-devtools"

[metadata.diem-devtools]
dir = "target/nextest"
junit = "junit.xml"
