## This is the default config used by nextest. It is embedded in the binary at build time.
## It may be used as a template for .config/nextest.toml.

[metadata]
## The directory under the workspace root at which metadata is written.
## Profile-specific metadata is written to dir/<profile-name>.
dir = "target/nextest"

## The prefix to use while naming the metadata. If aggregating test metadata across different
## test runs, it may be useful to provide separate names for each run.
prefix = "nextest-"

## This section defines the default nextest profile. Custom profiles are layered on top of the
## default profile.
[profile.default]
## "retries" defines the number of times a test should be retried. If set to a non-zero value, tests that
## succeed on a subsequent attempt will be marked as non-flaky. Can be overridden through the `--retries`
## option.
retries = 0

## "failure-output" defines when test failures are output to standard output. Accepted values are
## * "immediate": output failures as soon as they happen
## * "final": output failures at the end of the test run
## * "immediate-final": output failures as soon as they happen and at the end of the test run
## * "never": don't output failures at all
##
## For large test suites and CI it may be useful to use "immediate-final".
failure-output = "immediate"

[profile.default.junit]
## Output metadata in the JUnit format into the given file inside 'metadata.dir/<profile-name>'. If unspecified, JUnit
## is not written out.
## path = "junit.xml"
