[package]
name = "nextest-summaries"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"

[dependencies]
camino = { version = "1.0.5", features = ["serde1"] }
serde = { version = "1.0.130", features = ["derive"] }
